### ISSUE TITLE
Update Clients & Tools page

### ISSUE THREAD

**Issue by mechanomi** [crate/crate-clients-tools#1]
###  Documentation feedback

 
- Page title: CrateDB Clients and Tools
- Page URL: https://crate.io/docs/crate/client-tools/en/latest/index.html
- Source: https://github.com/crate/crate-clients-tools/blob/master/docs/index.rst

---

@joemoe reported that Azure Functions and R are missing from this page

**Comment by mechanomi** [comment]
@joemoe can you provide more details? what would you like to include/add here, explicitly?

**Comment by joemoe** [comment]
I'd also scan our blogposts. E.g. we can add SQL Pad and also link external blogposts like this. 
https://devblogs.microsoft.com/azure-sql/querying-and-visualizing-data-using-sqlpad/

**Comment by infoverload** [comment]
Tied to https://github.com/crate/tech-writing-domain/issues/106

**Comment by infoverload** [comment]
Related to https://trello.com/c/4Wi958uf/67-how-to-blogpost-pentaho-old-card
