### ISSUE TITLE
Update Looker

### ISSUE THREAD

**Issue by amotl** [crate/crate-clients-tools#19]
Hi again,

issues with Looker apparently have been resolved, see https://github.com/crate/crate/issues/9663#issuecomment-789742882. So, we might want to update the documentation about it.

With kind regards,
Andreas.

**Comment by mechanomi** [comment]
@amotl put this in the icebox. but if you wanna do this, please be my guest!

**Comment by amotl** [comment]
Added to the [backlog](../blob/main/BACKLOG.md) file.
