### ISSUE TITLE
link to latest version results in 404

### ISSUE THREAD

**Issue by msbt** [crate/crate-clients-tools#2]
###  Documentation feedback

 
- Page title: CrateDB Clients and Tools
- Page URL: https://crate.io/docs/crate/client-tools/en/latest/index.html
- Source: https://github.com/crate/crate-clients-tools/blob/master/docs/index.rst

---

when clicking on latest, href points to
https://crate.io/docs/crate/client-tools/en/latest/
instead of
https://crate.io/docs/crate/clients-tools/en/latest/

**Comment by mechanomi** [comment]
@msbt thanks for the issue report!

can you give me the URL of the page with the broken link, please? I can't seem to find it

**Comment by msbt** [comment]
it is actually on that page: https://crate.io/docs/crate/clients-tools/en/latest/ - if you click on latest there, you get forwarded to 404 (probably a similar issue as with admin-ui the other day)

**Comment by mechanomi** [comment]
aha, thanks @msbt

**Comment by infoverload** [comment]
Fixed
