### ISSUE TITLE
Problem running MLFlow with CrateDB

### ISSUE THREAD

**Issue by amotl** [crate/crate-clients-tools#47]
Hi there,

@andnig recently evaluated [MLflow] with CrateDB. Thanks!

> MLflow can be used to track ML experiments - see [here](https://mlflow.org/docs/latest/tracking.html#scenario-4-mlflow-with-remote-tracking-server-backend-and-artifact-stores) for more details. Conveniently, it allows to use a PostgreSQL database backend. In theory, we would be able to use CrateDB as MLflow backend as well, removing the need to have yet another database in our MLOps environments.

However, when running the MLflow server, the following exception is raised:

```python
2023/07/31 09:02:39 WARNING mlflow.store.db.utils: SQLAlchemy engine could not be created. The following exception is caught.
(psycopg2.errors.InternalError_) line 1:1: mismatched input 'ROLLBACK' expecting
```

#### Reproduce
1. Install [mlflow](https://pypi.org/project/mlflow/) and [psycopg2](https://pypi.org/project/psycopg2/) packages. `pip install mlflow 'psycopg2[binary]'`

2. Run  ``mlflow server --backend-store-uri='postgresql://<crate-user>:<crate-pwd>@<crate-instance>.azure.cratedb.net:5432' --host 0.0.0.0 --port 8885``

With kind regards,
Andreas.

[MLflow]: https://mlflow.org/

**Comment by seut** [comment]
This is done after talking with @amotl.
