### ISSUE TITLE
JavaScript: Re-add `node-crate` package

### ISSUE THREAD

**Issue by amotl** [crate/crate-clients-tools#56]
## About

Coming from https://github.com/crate/crate-sample-apps/pull/140, we should re-add [node-crate](https://github.com/megastef/node-crate) by @megastef to the documentation.
It apparently got lost when refactoring from the [legacy documentation section](https://cratedb.com/docs/crate/clients-tools/en/latest/legacy.html).

The library is well alive and maintained, thank you Stefan.

**Comment by amotl** [comment]
The application https://github.com/simonprickett/cratedb-demo by @simonprickett also uses `node-crate`. Cheers.
GH-60 will re-add it to the documentation section about [Database Drivers](https://cratedb.com/docs/crate/clients-tools/en/latest/connect/#client-libraries). Please let us know if you would like to see any wording changes.

**Comment by simonprickett** [comment]
Sounds good to me - I'll be finishing the README and a few other little bits and pieces for my application in the next few days - thanks for wanting to link to it.

**Comment by amotl** [comment]
Hi Simon. In this context, it is just about re-adding an item about the `node-crate` driver to the documentation. On the other hand, we will be happy to present your project on the community forum at https://community.cratedb.com/. Feel free to write an article by yourself if you like this idea.

**Comment by amotl** [comment]
Hi again. GH-60 has been merged. Closing this. Thanks Simon.
